// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Nexo.Api.Infrastructure.Persistence;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Nexo.Api.Migrations
{
    [DbContext(typeof(NexoDbContext))]
    [Migration("20260929011913_AddPlanPricingAndFeatures")]
    partial class AddPlanPricingAndFeatures
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Nexo.Api.Domain.Models.Account", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<string>("FirstName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("InvitationCodeHash")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime?>("InvitationExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("InvitationTokenHash")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("LastName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("OrganizationId");

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("Nexo.Api.Domain.Models.ExternalLogin", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("ProviderKey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("Provider", "ProviderKey")
                        .IsUnique();

                    b.ToTable("ExternalLogins");
                });

            modelBuilder.Entity("Nexo.Api.Domain.Models.Organization", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("PlanId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PlanId");

                    b.ToTable("Organizations");
                });

            modelBuilder.Entity("Nexo.Api.Domain.Models.Plan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("HasAiInsights")
                        .HasColumnType("boolean");

                    b.Property<bool>("HasDecisionHistory")
                        .HasColumnType("boolean");

                    b.Property<bool>("HasExpenseTracking")
                        .HasColumnType("boolean");

                    b.Property<bool>("HasIncidentTracking")
                        .HasColumnType("boolean");

                    b.Property<bool>("HasPrioritySupport")
                        .HasColumnType("boolean");

                    b.Property<int>("MemberLimit")
                        .HasColumnType("integer");

                    b.Property<decimal?>("MonthlyPrice")
                        .HasPrecision(8, 2)
                        .HasColumnType("numeric(8,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("ResourceLimit")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Plans");

                    b.HasData(
                        new
                        {
                            Id = new Guid("6f1c2b1e-7a52-4d0a-9a53-1f3e5c0b8d01"),
                            HasAiInsights = false,
                            HasDecisionHistory = false,
                            HasExpenseTracking = false,
                            HasIncidentTracking = false,
                            HasPrioritySupport = false,
                            MemberLimit = 20,
                            MonthlyPrice = 0m,
                            Name = "Free",
                            ResourceLimit = 10
                        },
                        new
                        {
                            Id = new Guid("8b2d4f3a-9c61-4e2b-8a64-2f4e6c0b9d02"),
                            HasAiInsights = false,
                            HasDecisionHistory = true,
                            HasExpenseTracking = true,
                            HasIncidentTracking = true,
                            HasPrioritySupport = false,
                            MemberLimit = 100,
                            MonthlyPrice = 29m,
                            Name = "Team",
                            ResourceLimit = 100
                        },
                        new
                        {
                            Id = new Guid("a1e5c7d4-1b83-4f0c-9b75-3a5f7d1c0e03"),
                            HasAiInsights = true,
                            HasDecisionHistory = true,
                            HasExpenseTracking = true,
                            HasIncidentTracking = true,
                            HasPrioritySupport = true,
                            MemberLimit = 2147483647,
                            Name = "Enterprise",
                            ResourceLimit = 2147483647
                        });
                });

            modelBuilder.Entity("Nexo.Api.Domain.Models.Account", b =>
                {
                    b.HasOne("Nexo.Api.Domain.Models.Organization", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Nexo.Api.Domain.Models.ExternalLogin", b =>
                {
                    b.HasOne("Nexo.Api.Domain.Models.Account", null)
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Nexo.Api.Domain.Models.Organization", b =>
                {
                    b.HasOne("Nexo.Api.Domain.Models.Plan", "Plan")
                        .WithMany()
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Plan");
                });
#pragma warning restore 612, 618
        }
    }
}
