#requires -Version 7.0
[CmdletBinding()]
param(
    [string]$DocsPath = (Join-Path $PSScriptRoot '../../docs')
)

$ErrorActionPreference = 'Stop'
$repoRoot = [IO.Path]::GetFullPath((Join-Path $PSScriptRoot '../..'))
$docsRoot = (Resolve-Path -LiteralPath $DocsPath).Path
$marker = '<!-- Generated by Nexo PlantUML generator. Do not edit. -->'
$sources = @(Get-ChildItem -LiteralPath $docsRoot -Recurse -File -Filter '*.puml' | Sort-Object FullName)
$expected = [Collections.Generic.HashSet[string]]::new([StringComparer]::Ordinal)
$pending = @()
$tempRoot = $null

try {
    if ($sources.Count -gt 0) {
        $null = Get-Command java -ErrorAction Stop
        $pin = Get-Content -Raw -LiteralPath (Join-Path $repoRoot 'libs/plantuml.json') | ConvertFrom-Json
        if ($pin.version -notmatch '^\d+\.\d+\.\d+$' -or $pin.sha256 -notmatch '^[a-f0-9]{64}$') {
            throw 'Invalid PlantUML version or checksum in libs/plantuml.json.'
        }
        $cache = Join-Path $repoRoot '.cache/plantuml'
        $null = New-Item -ItemType Directory -Force -Path $cache
        $jar = Join-Path $cache "plantuml-$($pin.version).jar"
        if (-not (Test-Path -LiteralPath $jar)) {
            $download = "$jar.download"
            try {
                $url = "https://github.com/plantuml/plantuml/releases/download/v$($pin.version)/plantuml-$($pin.version).jar"
                Invoke-WebRequest -Uri $url -OutFile $download
                if ((Get-FileHash -LiteralPath $download -Algorithm SHA256).Hash.ToLowerInvariant() -ne $pin.sha256) {
                    throw 'Downloaded PlantUML JAR failed checksum verification.'
                }
                Move-Item -LiteralPath $download -Destination $jar
            } finally {
                if (Test-Path -LiteralPath $download) { Remove-Item -LiteralPath $download }
            }
        }
        if ((Get-FileHash -LiteralPath $jar -Algorithm SHA256).Hash.ToLowerInvariant() -ne $pin.sha256) {
            throw "Cached PlantUML JAR failed checksum verification: $jar"
        }

        $tempRoot = Join-Path $cache ([Guid]::NewGuid().ToString())
        $null = New-Item -ItemType Directory -Path $tempRoot
        foreach ($source in $sources) {
            if ($source.Directory.Name -cne 'puml') {
                throw "Place diagram sources in a puml/ folder: $($source.FullName)"
            }
            $content = Get-Content -Raw -LiteralPath $source.FullName
            if ([regex]::Matches($content, '(?m)^\s*@startuml\s*$').Count -ne 1 -or
                [regex]::Matches($content, '(?m)^\s*@start').Count -ne 1 -or
                [regex]::Matches($content, '(?m)^\s*@enduml\s*$').Count -ne 1) {
                throw "Use one unnamed @startuml / @enduml block per file: $($source.FullName)"
            }
            $output = Join-Path $source.Directory.Parent.FullName "svg/$($source.BaseName).svg"
            if (-not $expected.Add($output)) { throw "Duplicate diagram output: $output" }
            $staging = Join-Path $tempRoot ($pending.Count.ToString())
            $null = New-Item -ItemType Directory -Path $staging
            & java '-Djava.awt.headless=true' '-DPLANTUML_SECURITY_PROFILE=SANDBOX' -jar $jar -charset UTF-8 -tsvg -nometadata -failfast2 -o $staging $source.FullName
            if ($LASTEXITCODE -ne 0) { throw "PlantUML failed: $($source.FullName)" }
            $rendered = @(Get-ChildItem -LiteralPath $staging -Filter '*.svg' -File)
            if ($rendered.Count -ne 1) { throw "Expected one SVG for $($source.FullName)." }
            $svg = Get-Content -Raw -LiteralPath $rendered[0].FullName
            $xml = [xml]$svg
            if ($xml.DocumentElement.LocalName -ne 'svg') { throw "Invalid SVG: $($source.FullName)" }
            $pending += @{ Output = $output; Content = "$marker`n$svg" }
        }
    }

    # Publish only after every source has rendered successfully.
    foreach ($item in $pending) {
        $null = New-Item -ItemType Directory -Force -Path (Split-Path $item.Output)
        [IO.File]::WriteAllText($item.Output, $item.Content, [Text.UTF8Encoding]::new($false))
        Write-Host "Generated $($item.Output)"
    }
    # Only remove stale outputs owned by this generator; preserve hand-drawn SVGs.
    foreach ($svg in Get-ChildItem -LiteralPath $docsRoot -Recurse -File -Filter '*.svg') {
        if ($svg.Directory.Name -ceq 'svg' -and -not $expected.Contains($svg.FullName) -and
            (Get-Content -LiteralPath $svg.FullName -TotalCount 1) -ceq $marker) {
            Remove-Item -LiteralPath $svg.FullName
            Write-Host "Removed stale output $($svg.FullName)"
        }
    }
    Write-Host "Rendered $($sources.Count) diagram(s)."
} finally {
    if ($tempRoot -and (Test-Path -LiteralPath $tempRoot)) {
        $resolvedTemp = (Resolve-Path -LiteralPath $tempRoot).Path
        $cachePrefix = [IO.Path]::GetFullPath((Join-Path $repoRoot '.cache/plantuml')) + [IO.Path]::DirectorySeparatorChar
        if (-not $resolvedTemp.StartsWith($cachePrefix, [StringComparison]::OrdinalIgnoreCase)) {
            throw 'Refusing to clean a staging directory outside the PlantUML cache.'
        }
        Remove-Item -LiteralPath $resolvedTemp -Recurse -Force
    }
}
