#requires -Version 7.0
[CmdletBinding()]
param()

$ErrorActionPreference = 'Stop'
$generator = Join-Path $PSScriptRoot 'generate-plantuml-diagrams.ps1'
$testRoot = Join-Path ([IO.Path]::GetTempPath()) ([Guid]::NewGuid().ToString())
$pumlDir = Join-Path $testRoot 'sample/puml'
$svgDir = Join-Path $testRoot 'sample/svg'
$null = New-Item -ItemType Directory -Force -Path $pumlDir

try {
    # A valid source renders one SVG with the ownership marker.
    Set-Content -LiteralPath (Join-Path $pumlDir 'ok.puml') -Value "@startuml`nAlice -> Bob: hi`n@enduml"
    & $generator -DocsPath $testRoot
    $svgPath = Join-Path $svgDir 'ok.svg'
    if (-not (Test-Path -LiteralPath $svgPath)) { throw "Expected $svgPath to be generated." }
    if ((Get-Content -LiteralPath $svgPath -TotalCount 1) -notmatch '^<!-- Generated by Nexo PlantUML generator') {
        throw 'Generated SVG is missing the ownership marker.'
    }
    Write-Host 'PASS: valid source renders an SVG'

    # Removing the source removes the SVG it owns, but not hand-drawn SVGs.
    Remove-Item -LiteralPath (Join-Path $pumlDir 'ok.puml')
    $null = New-Item -ItemType Directory -Force -Path $svgDir
    Set-Content -LiteralPath (Join-Path $svgDir 'handmade.svg') -Value '<svg></svg>'
    & $generator -DocsPath $testRoot
    if (Test-Path -LiteralPath $svgPath) { throw 'Stale generated SVG was not removed.' }
    if (-not (Test-Path -LiteralPath (Join-Path $svgDir 'handmade.svg'))) { throw 'Hand-drawn SVG was wrongly removed.' }
    Write-Host 'PASS: stale outputs are removed, hand-drawn SVGs are preserved'

    # A malformed source (no @enduml) must fail, not produce partial output.
    Set-Content -LiteralPath (Join-Path $pumlDir 'bad.puml') -Value "@startuml`nAlice -> Bob: hi"
    $threw = $false
    try { & $generator -DocsPath $testRoot } catch { $threw = $true }
    if (-not $threw) { throw 'Malformed source should have failed generation.' }
    Write-Host 'PASS: malformed source fails generation'
} finally {
    Remove-Item -LiteralPath $testRoot -Recurse -Force -ErrorAction SilentlyContinue
}

Write-Host 'All generator tests passed.'
